services:
  app:
    build:
      context: .
      dockerfile: app.Dockerfile
    volumes:
      - ../:/var/www
      - ../public:/var/www/html
      - ../tmp/xdebug:/tmp/xdebug
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf.template:ro
      - ./auth_cas.conf:/etc/apache2/mods-available/auth_cas.conf.template:ro
    ports:
      - "${APP_HTTP_PORT:-8080}:80"
      - "${APP_HTTPS_PORT:-8443}:443"
    environment:
      - APP_HTTPS_PORT=${APP_HTTPS_PORT:-8443}
    depends_on:
      database:
        condition: service_healthy
      mailcatcher:
        condition: service_started
    env_file:
      - ../app.env
  database:
    image: mysql:8.4
    expose:
      - "3306"
    ports:
      - "9906:3306"
    volumes:
      - ../tmp/mysql:/var/lib/mysql
    env_file:
      - ../database.env
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 20
  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"